version: '3.5'

services:
  app:
    build: .
    environment:
      TZ: Asia/Tokyo
    volumes:
      - .:/kokoko
    ports:
      - 8089:8089
      - 12345:12345
volumes:
  link-AG-db:
    driver: local
